	Tabla PERFIL:

CREATE TABLE PERFIL(
PERFIL VARCHAR2(13) PRIMARY KEY
);

--------------------------------------------------------------------
	Tabla SOCIO:

He creado una secuencia auto incremental para el código de socio:
	  
CREATE SEQUENCE INCREMENTO_IDSOCIOS
INCREMENT BY 1
START WITH 0
MINVALUE 0;

CREATE  TABLE SOCIO (
	ID_SOCIO NUMBER NOT NULL PRIMARY KEY,
	NOMBRE VARCHAR2(25) NOT NULL,
	APELLIDOS VARCHAR2(25) NOT NULL,
	FECHA_NACIMIENTO DATE NOT NULL,
	DNI VARCHAR2(10),
	TELF VARCHAR2(14),
	EMAIL VARCHAR2(25),
	FECHA_ALTA_CLUB DATE NOT NULL,
	FECHA_BAJA_CLUB DATE,
PERFIL_ACCESO VARCHAR2(13),
	REPRESENTANTE NUMBER,
	CONSTRAINT SOC_IDS_FK FOREIGN KEY (ID_SOCIO) REFERENCES SOCIO (ID_SOCIO),
	CONSTRAINT SOC_PER_FK FOREIGN KEY(PERFIL_ACCESO) REFERENCES PERFIL(PERFIL)
);

--------------------------------------------------------------------
	Tabla CUOTA:

He creado una secuencia auto incremental para el código de cuota:
CREATE SEQUENCE INCREMENTO_CUOTAS
INCREMENT BY 1
START WITH 0
MINVALUE 0;

CREATE  TABLE CUOTA(
ID_CUOTA NUMBER NOT NULL PRIMARY KEY,
PRECIO_ADULTO NUMBER,
PRECIO_MENOR NUMBER,
ANYO DATE
);

--------------------------------------------------------------------
	Tabla CUOTAPAGADA:

CREATE TABLE CUOTAPAGADA (
ID_SOCIO NUMBER NOT NULL,
ID_CUOTA NUMBER NOT NULL, 
FECHA DATE,
PAGADO VARCHAR2(2), 
CONSTRAINT CUOPA_PK PRIMARY KEY(ID_SOCIO, ID_CUOTA),
CONSTRAINT SO_IDS_FK FOREIGN KEY (ID_SOCIO) REFERENCES SOCIO(ID_SOCIO),
CONSTRAINT CUO_IDC_FK FOREIGN KEY (ID_CUOTA) REFERENCES CUOTA (ID_CUOTA)
      );
	  
--------------------------------------------------------------------
	Tabla TIPOACTIVIDAD:

CREATE TABLE TIPOACTIVIDAD(
ID_TIPO_ACTIVIDAD NUMBER PRIMARY KEY,
DESCRIPCION VARCHAR2(25)
);


--------------------------------------------------------------------
	Tabla DIFICULTAD:

CREATE TABLE DIFICULTAD(
DIFICULTAD VARCHAR2(5) PRIMARY KEY
);


--------------------------------------------------------------------
	Tabla ACTIVIDAD:

He creado una secuencia auto incremental para id de actividad:
CREATE SEQUENCE INCREMENTO_IDACTIVIDAD
INCREMENT BY 1
START WITH 0
MINVALUE 0;

CREATE TABLE ACTIVIDAD (
ID_ACTIVIDAD NUMBER NOT NULL PRIMARY KEY,
DESCRIPCION VARCHAR2(50) NOT NULL,
FECHA DATE NOT NULL,
PRECIO NUMBER(4,2),
SUSPENDIDA VARCHAR2(2), 
MOTIVO_SUSPENSION VARCHAR2(50),
DIFICULTAD VARCHAR2(5),
ORGANIZADOR NUMBER NOT NULL,
TIPOACTIVIDAD NUMBER NOT NULL, 
CONSTRAINT ACT_ORG_FK FOREIGN KEY (ORGANIZADOR) REFERENCES SOCIO (ID_SOCIO),
CONSTRAINT ACT_TIP_FK FOREIGN KEY (TIPOACTIVIDAD) REFERENCES   TIPOACTIVIDAD(ID_TIPO_ACTIVIDAD),
CONSTRAINT ACT_DIF_FK FOREIGN KEY (DIFICULTAD) REFERENCES DIFICULTAD (DIFICULTAD)
      );
	  
	  
--------------------------------------------------------------------
	Tabla SOCIOPARTICIPA:

CREATE TABLE SOCIOPARTICIPA (
ID_ACTIVIDAD NUMBER NOT NULL,
ID_PARTICIPANTE NUMBER NOT NULL,
CONSTRAINT SP_PK PRIMARY KEY(ID_ACTIVIDAD, ID_PARTICIPANTE),
CONSTRAINT SOC_ID_FK FOREIGN KEY (ID_PARTICIPANTE) REFERENCES SOCIO(ID_SOCIO),
CONSTRAINT ACT_ID_FK FOREIGN KEY (ID_ACTIVIDAD) REFERENCES ACTIVIDAD (ID_ACTIVIDAD)
      );
	  
--------------------------------------------------------------------
	Tabla JUNTA:

CREATE SEQUENCE INCREMENTO_JUNTAS
INCREMENT BY 1
START WITH 0
MINVALUE 0;

CREATE TABLE JUNTA(
ID_JUNTA NUMBER NOT NULL PRIMARY KEY,
PRESIDENTE NUMBER CONSTRAINT SOC_IDP_FK REFERENCES SOCIO,
VICEPRESIDENTE NUMBER CONSTRAINT SOV_IDS_FK  REFERENCES SOCIO,
SECRETARIO NUMBER CONSTRAINT SOC_ISE_FK REFERENCES SOCIO,
TESORERO NUMBER CONSTRAINT SOC_IDT_FK  REFERENCES SOCIO,
VOCAL1 NUMBER CONSTRAINT SOC_ID1_FK REFERENCES SOCIO,
VOCAL2 NUMBER CONSTRAINT SOC_ID2_FK  REFERENCES SOCIO,
VOCAL3 NUMBER CONSTRAINT SOC_ID3_FK  REFERENCES SOCIO,
VOCAL4 NUMBER CONSTRAINT SOC_ID4_FK REFERENCES SOCIO,
VOCAL5 NUMBER CONSTRAINT SOC_ID5_FK REFERENCES SOCIO,
FECHA_INICIO DATE,
FECHA_FIN DATE
);



--------------------------------------------------------------------
	Tabla ACTIVIDADJUNTA:

CREATE TABLE ACTIVIDADJUNTA(
ID_ACTIVIDAD NUMBER NOT NULL,
ID_JUNTA NUMBER NOT NULL,
CONSTRAINT AJ_PK PRIMARY KEY(ID_ACTIVIDAD, ID_JUNTA),
CONSTRAINT  ACT_IDJ_FK FOREIGN KEY (ID_JUNTA) REFERENCES JUNTA(ID_JUNTA),
CONSTRAINT ACT_IDA_FK FOREIGN KEY (ID_ACTIVIDAD) REFERENCES ACTIVIDAD (ID_ACTIVIDAD)
);

